INSERT INTO Employee (EmpId, EmpName, Email, Technology, Lead, WorkLocation) VALUES
	('122', 'Sreekar Sudireddy', 'sreekars@techigai.io', '.NET', '193', 'N-Heights'),
	('123', 'Sriram Gundabattula', 'sriramg@techigai.io', '.NET', '124', 'N-Heights'),
	('124', 'Nishanth Venumula', 'nishanthv@techigai.io', '.NET', '193', 'N-Heights'),
	('125', 'Maheshwar Kondapur', 'maheshk@techigai.io', 'Data Science', '174', 'N-Heights'),
	('126', 'Praveen Jangili', 'praveen.jangili@techigai.io', 'Data Engineering', '208', 'Aurobindo'),
	('127', 'Agasthya Kommuri', 'agasthya.kommuri@techigai.io', 'BA', '176', 'N-Heights'),
	('129', 'Deepthi Naredla', 'deepthi.naredla@techigai.io', '.NET', '176', 'Virtual'),
	('130', 'Vamshikrishna Siddamshetty', 'vamshi.siddamshetty@techigai.io', 'Data Engineering', '208', 'Aurobindo'),
	('131', 'Kavya Gogineni', 'kavya.gogineni@techigai.io', 'Data Engineering', '265', 'Aurobindo'),
	('132', 'Divyansh Agarwal', 'divyansh.agarwal@techigai.io', 'Platform Engineering', '175', 'N-Heights'),
	('133', 'Ketan Jain', 'ketan.jain@techigai.io', 'Data Engineering', '266', 'Aurobindo'),
	('134', 'Shaik Faizuddin', 'faiz.shaik@techigai.io', '.NET', '129', 'N-Heights'),
	('137', 'Ritwik Bojja', 'ritwik.bojja@techigai.io', '.NET', '122', 'N-Heights'),
	('138', 'Pavan Gunda', 'pavan.gunda@techigai.io', '.NET', '387', 'N-Heights'),
	('141', 'Jaideep Yerramsetti', 'jaideep.yerramsetti@techigai.io', 'ROR', '338', 'Aurobindo'),
	('142', 'Anirudh Govardhanam', 'anirudh.govardhanam@techigai.io', 'Data Engineering', '266', 'Aurobindo'),
	('143', 'Divya Duddukuri', 'divya.duddukuri@techigai.io', 'Platform Engineering', '175', 'N-Heights'),
	('147', 'Vidyasagar Sakaray', 'vidyasagar.sakaray@techigai.io', 'Quality Engineering', '179', 'N-Heights'),
	('150', 'Sruthi Pasumarthi', 'sruthi.pasumarthi@techigai.io', 'Quality Engineering', '183', 'N-Heights'),
	('151', 'Pavani Kotamarthi', 'pavani.kotamarthi@techigai.io', 'Front End', '166', 'Aurobindo'),
	('152', 'Sravani Allu', 'sravani.allu@techigai.io', 'Quality Engineering', '183', 'N-Heights'),
	('155', 'Mahidhar Vukkem', 'mahidhar.vukkem@techigai.io', 'PHP', '174', 'N-Heights'),
	('157', 'Chandana Vipparla', 'chandana.vipparla@techigai.io', 'Front End', '122', 'N-Heights'),
	('158', 'Bhanu Ayinala', 'bhanu.ayinala@techigai.io', 'ROR', '190', 'Aurobindo'),
	('162', 'Narasimha Shyamala', 'narasimha.shyamala@techigai.io', 'SNA', '190', 'Aurobindo'),
	('163', 'Naveena Sadhu', 'naveena.sadhu@techigai.io', 'TA', '189', 'N-Heights'),
	('165', 'Jeevan Barnana', 'jeevan.barnana@techigai.io', 'Finance', '193', 'N-Heights'),
	('166', 'Nikitha Sidda', 'nikitha.sidda@techigai.io', 'Front End', '122', 'N-Heights'),
	('170', 'Eshwar Kyatham', 'eshwark@techigai.io', '.NET', '122', 'N-Heights'),
	('171', 'Sravan Kankanala', 'sravan.kankanala@techigai.io', 'Finance', '165', 'N-Heights'),
	('174', 'Pavan Seepana', 'pavan.seepana@techigai.io', 'BA', '193', 'N-Heights'),
	('175', 'Prashanth Venumula', 'prashanthv@techigai.io', '.NET', '190', 'N-Heights'),
	('176', 'Abhijith Ponnapally', 'abhip@techigai.io', '.NET', '193', 'N-Heights'),
	('177', 'Nikhil Goud', 'nikhil.goud@techigai.io', '.NET', '193', 'N-Heights'),
	('179', 'Vinay Chintapally', 'vinayc@techigai.io', 'Quality Engineering', '176', 'N-Heights'),
	('182', 'Venkatesh Chinthakindi', 'venkatesh.chinthakindi@techigai.io', '.NET', '124', 'N-Heights'),
	('183', 'Tejaswi Appala', 'tejaswia@techigai.io', 'Quality Engineering', '124', 'N-Heights'),
	('184', 'Lokesh Betha', 'lokesh.betha@techigai.io', '.NET', '124', 'N-Heights'),
	('186', 'Venkat Seelam', 'venkata.seelam@techigai.io', 'Android', '224', 'Aurobindo'),
	('187', 'Vikas Kumar', 'vikask@techigai.io', 'BD', '193', 'N-Heights'),
	('188', 'Chandrakala Bara', 'chandrakala.bara@techigai.io', 'Quality Engineering', '179', 'Aurobindo'),
	('189', 'Ravinder Konyala', 'ravinder.konyala@techigai.io', 'TA', '193', 'N-Heights'),
	('190', 'Sireesha Alapati', 'sireesha.alapati@techigai.io', 'Project Management', '193', 'Aurobindo'),
	('193', 'Raghav Kandanelly', 'raghav.kandanelly@techigai.io', 'Project Management', '193', 'N-Heights'),
	('194', 'Aditya Vajjala', 'aditya.vajjala@techigai.io', '.NET', '190', 'Aurobindo'),
	('195', 'Karthik Konkula', 'karthik.konkula@techigai.io', '.NET', '193', 'N-Heights'),
	('196', 'Srikanth Kantamaneni', 'srikanth.kantamaneni@techigai.io', 'Data Engineering', '208', 'Aurobindo'),
	('199', 'Prem Ambati', 'prem.ambati@techigai.io', 'Quality Engineering', '183', 'N-Heights'),
	('200', 'Santosh Gongada', 'santosh@techigai.io', 'HR', '200', 'N-Heights'),
	('202', 'Satya Penmetsa', 'satya.penmetsa@techigai.io', '.NET', '124', 'N-Heights'),
	('204', 'Yeshwanth Vadde', 'yeshwanth.vadde@techigai.io', 'BA', '124', 'N-Heights'),
	('206', 'Sravan Kanchanapalli', 'sravan.kanchanapalli@techigai.io', 'Quality Engineering', '183', 'N-Heights'),
	('207', 'Dhanush Thoutam', 'dhanush.thoutam@techigai.io', 'Marketing', '294', 'N-Heights'),
	('208', 'Shiva Bodepudi', 'shiva.bodepudi@techigai.io', 'Data Engineering', '190', 'Aurobindo'),
	('210', 'Sai Jonnada', 'sai.jonnada@techigai.io', 'Java', '190', 'Aurobindo'),
	('213', 'Swathi Vorsu', 'swathi.vorsu@techigai.io', 'ROR', '338', 'Aurobindo'),
	('215', 'Amrutha Chenna', 'amrutha.chenna@techigai.io', '.NET', '122', 'N-Heights'),
	('216', 'Chandrakanth Nettem', 'chandrakanth.nettem@techigai.io', 'Quality Engineering', '190', 'Aurobindo'),
	('218', 'Dileep Ravula', 'dileep.ravula@techigai.io', '.NET', '174', 'N-Heights'),
	('221', 'Preetham Chenna', 'preetham.chenna@techigai.io', 'ROR', '194', 'Aurobindo'),
	('222', 'Anuradha Konda', 'anuradha.konda@techigai.io', 'Project Management', '200', 'Aurobindo'),
	('224', 'Pruthvi Paruchuri', 'pruthvi.paruchuri@techigai.io', 'iOS', '190', 'Aurobindo'),
	('230', 'Harsh Singhvi', 'harsh.singhvi@techigai.io', 'Data Engineering', '343', 'Aurobindo'),
	('231', 'Manasa Agathamudi', 'manasa.agathamudi@techigai.io', 'Data Engineering', '433', 'Aurobindo'),
	('232', 'Balanageswar Bhuvanagiri', 'balanageswar.bhuvanagiri@techigai.io', '.NET', '269', 'N-Heights'),
	('233', 'Nageswar Chedella', 'nageswar.chedella@techigai.io', 'ROR', '194', 'Aurobindo'),
	('234', 'Ramya Chitti', 'ramya.chitti@techigai.io', 'PHP', '388', 'N-Heights'),
	('235', 'Vinay Gaddamedi', 'vinay.gaddamedi@techigai.io', 'Platform Engineering', '175', 'N-Heights'),
	('236', 'Ashok Murukutla', 'ashok.murukutla@techigai.io', 'Data Engineering', '340', 'Aurobindo'),
	('237', 'Gagan Pasupuleti', 'gagan.pasupuleti@techigai.io', 'Platform Engineering', '175', 'N-Heights'),
	('239', 'Sathwik Sinde', 'sathwik.sinde@techigai.io', 'Data Engineering', '130', 'Aurobindo'),
	('244', 'Bhuvanesh Sutraye', 'bhuvanesh.sutraye@techigai.io', 'ROR', '338', 'Aurobindo'),
	('246', 'Neeraja Mandha', 'neeraja.mandha@techigai.io', 'Quality Engineering', '391', 'Aurobindo'),
	('250', 'Sairam Kalavala', 'sairam.kalavala@techigai.io', '.NET', '122', 'N-Heights'),
	('251', 'Maneesh D', 'maneesh.d@techigai.io', 'Data Engineering', '391', 'Aurobindo'),
	('253', 'Sridivya Gangaraju', 'sridivya.gangaraju@techigai.io', 'PMO', '193', 'N-Heights'),
	('255', 'Yuva Sekhar Chennareddy', 'yuvasekhar.chennareddy@techigai.io', '.NET', '176', 'N-Heights'),
	('257', 'Srihari Adabala', 'srihari.adabala@techigai.io', 'Data Engineering', '266', 'Aurobindo'),
	('259', 'Sravan Jinnareddy', 'sravan.jinnareddy@techigai.io', '.NET', '202', 'N-Heights'),
	('260', 'Harshavardhan Sane', 'harshavardhan.sane@techigai.io', 'Data Engineering', '266', 'Aurobindo'),
	('261', 'Saipraneeth Konda', 'saipraneeth.konda@techigai.io', 'Data Engineering', '208', 'Aurobindo'),
	('262', 'Amith Thiruveedhi', 'amith.thiruveedhi@techigai.io', 'Data Engineering', '251', 'Aurobindo'),
	('264', 'Ramya Kuppala', 'ramya.kuppala@techigai.io', 'Data Engineering', '200', 'Aurobindo'),
	('265', 'Prathyusha Chennareddy', 'prathyusha.chennareddy@techigai.io', 'Data Engineering', '208', 'Aurobindo'),
	('266', 'Revathi Valleti', 'revathi.valleti@techigai.io', 'Data Engineering', '208', 'Aurobindo'),
	('267', 'Sandeep Tadde', 'sandeep.tadde@techigai.io', 'Data Engineering', '433', 'Aurobindo'),
	('268', 'Vamsi Marreddy', 'vamsi.marreddy@techigai.io', 'Quality Engineering', '190', 'Aurobindo'),
	('269', 'Rashmi Gaddam', 'rashmi.gaddam@techigai.io', '.NET', '124', 'N-Heights'),
	('271', 'Rajeev Valleti', 'rajeev.valleti@techigai.io', 'Data Engineering', '251', 'Aurobindo'),
	('272', 'Nikhila Marupally', 'nikhila.marupally@techigai.io', 'Quality Engineering', '194', 'Aurobindo'),
	('274', 'Divya Ravula', 'divya.ravula@techigai.io', 'Quality Engineering', '183', 'N-Heights'),
	('275', 'Pradeep Gurram', 'pradeep.gurram@techigai.io', 'Quality Engineering', '147', 'N-Heights'),
	('277', 'Alekhya Kothapally', 'alekhya.kothapally@techigai.io', 'Quality Engineering', '391', 'Aurobindo'),
	('279', 'Dharalika Donakanti', 'dharalika.donakanti@techigai.io', 'Quality Engineering', '129', 'N-Heights'),
	('282', 'Naveen Manthri', 'naveen.manthri@techigai.io', '.NET', '414', 'N-Heights'),
	('283', 'Himabindhu Buska', 'himabindhu.buska@techigai.io', '.NET', '387', 'N-Heights'),
	('284', 'Akila Ranga', 'akila.ranga@techigai.io', '.NET', '170', 'N-Heights'),
	('285', 'Saidivya Gunti', 'saidivya.gunti@techigai.io', '.NET', '129', 'N-Heights'),
	('286', 'Shiva Bopparaju', 'shiva.bopparaju@techigai.io', 'SNA', '162', 'N-Heights'),
	('287', 'Manohar Sama', 'manohar.sama@techigai.io', '.NET', '387', 'N-Heights'),
	('288', 'Goutham Miriyala', 'goutham.miriyala@techigai.io', '.NET', '414', 'N-Heights'),
	('289', 'Nikhila Kalaveni', 'nikhila.kalaveni@techigai.io', '.NET', '176', 'N-Heights'),
	('290', 'Shreya Valsa', 'shreya.valsa@techigai.io', 'Front End', '166', 'N-Heights'),
	('291', 'Dimple Tangeti', 'dimple.tangeti@techigai.io', '.NET', '129', 'N-Heights'),
	('292', 'Navaneetha Ragam', 'navaneetha.ragam@techigai.io', 'Front End', '166', 'N-Heights'),
	('294', 'Gayatri Yellayi', 'gayatri.yellayi@techigai.io', 'Marketing', '200', 'N-Heights'),
	('295', 'Bhargavi Mekala', 'bhargavi.mekala@techigai.io', '.NET', '176', 'N-Heights'),
	('296', 'Srijanraj Mekala', 'srijanraj.mekala@techigai.io', 'Python', '125', 'N-Heights'),
	('297', 'Niharika Anantha', 'niharika.anantha@techigai.io', '.NET', '122', 'N-Heights'),
	('298', 'Pavan Nagulapally', 'pavan.nagulapally@techigai.io', '.NET', '122', 'N-Heights'),
	('299', 'Preetham Koguru', 'preetham.koguru@techigai.io', 'Data Engineering', '343', 'Aurobindo'),
	('300', 'Vamsi Veerla', 'vamsi.veerla@techigai.io', 'JS', '510', 'Aurobindo'),
	('301', 'Abhinav Rajamur', 'abhinav.rajamur@techigai.io', 'Data Engineering', '130', 'Aurobindo'),
	('307', 'Ashish Darshi', 'ashish.darshi@techigai.io', 'Data Science', '125', 'N-Heights'),
	('308', 'Hari Devarapally', 'hari.devarapally@techigai.io', 'Data Engineering', '343', 'Aurobindo'),
	('309', 'Viswa Tupakula', 'viswa.tupakula@techigai.io', 'Mobile', '224', 'Aurobindo'),
	('310', 'Yashwanth Jannaikode', 'yashwanth.jannaikode@techigai.io', 'Platform Engineering', '175', 'N-Heights'),
	('311', 'Rishika Pamu', 'rishika.pamu@techigai.io', 'Data Engineering', '130', 'Aurobindo'),
	('312', 'Subhash Devulapalli', 'subhash.devulapalli@techigai.io', '.NET', '195', 'N-Heights'),
	('313', 'Karthik Raji', 'karthik.raji@techigai.io', 'Data Engineering', '343', 'Aurobindo'),
	('314', 'Koteswar Vysetti', 'koteswar.vysetti@techigai.io', '.NET', '387', 'N-Heights'),
	('316', 'Kaushik Veligatla', 'kaushik.veligatla@techigai.io', 'Data Engineering', '265', 'Aurobindo'),
	('317', 'Venkatesh Uppalanchi', 'venkatesh.uppalanchi@techigai.io', '.NET', '184', 'N-Heights'),
	('319', 'Saketha Navva', 'saketha.navva@techigai.io', '.NET', '170', 'N-Heights'),
	('320', 'Sreya Madhineni', 'sreya.madhineni@techigai.io', '.NET', '182', 'N-Heights'),
	('321', 'Monika Kunchanapally', 'monika.kunchanapally@techigai.io', 'Platform Engineering', '175', 'N-Heights'),
	('322', 'Naresh Rachuri', 'naresh.rachuri@techigai.io', 'Front End', '127', 'N-Heights'),
	('323', 'Juhitha Penumalli', 'juhitha.penumalli@techigai.io', '.NET', '176', 'N-Heights'),
	('324', 'Abdul Mohammed', 'abdul.mohammed@techigai.io', 'Front End', '122', 'N-Heights'),
	('327', 'Hemanvitha Kanisetty', 'hemanvitha.kanisetty@techigai.io', '.NET', '195', 'N-Heights'),
	('328', 'Chaitanya Bhogadi', 'chaitanya.bhogadi@techigai.io', 'Python', '125', 'N-Heights'),
	('329', 'Druvi Annamaneni', 'druvi.annamaneni@techigai.io', '.NET', '403', 'N-Heights'),
	('330', 'Prakash Puppala', 'prakash.puppala@techigai.io', '.NET', '202', 'N-Heights'),
	('333', 'Hanoop Ghanagam', 'hanoop.ghanagam@techigai.io', 'Java', '210', 'Aurobindo'),
	('334', 'Yeswanth Bellana', 'yeswanth.bellana@techigai.io', 'Admin', '200', 'Aurobindo'),
	('335', 'Mohith Palreddy', 'mohith.palreddy@techigai.io', 'BA', '124', 'N-Heights'),
	('336', 'Abhilash Damaragidda', 'abhilash.damaragidda@techigai.io', 'Data Engineering', '130', 'Aurobindo'),
	('338', 'Ashok Boya', 'ashok.boya@techigai.io', 'ROR', '194', 'Aurobindo'),
	('340', 'Chandra S', 'chandra.s@techigai.io', 'Data Engineering', '391', 'Aurobindo'),
	('341', 'Jayasri Bojja', 'jayasri.bojja@techigai.io', 'Data Engineering', '175', 'N-Heights'),
	('342', 'Shravya Sudireddy', 'shravya.sudireddy@techigai.io', 'RPA', '175', 'Virtual'),
	('343', 'Ram Reddymasi', 'ram.reddymasi@techigai.io', 'Data Engineering', '208', 'Aurobindo'),
	('344', 'Santhoshi Navath', 'santhoshi.navath@techigai.io', 'Quality Engineering', '176', 'N-Heights'),
	('345', 'Venugopal Avula', 'venugopal.avula@techigai.io', 'Quality Engineering', '183', 'N-Heights'),
	('347', 'Sowmya Sunkarapalli', 'sowmya.sunkarapalli@techigai.io', 'Quality Engineering', '179', 'N-Heights'),
	('348', 'Rajesh Mirdoddi', 'rajesh.mirdoddi@techigai.io', 'TA', '189', 'N-Heights'),
	('349', 'Chandra Bulla', 'chandra.bulla@techigai.io', 'Infra Ops', '175', 'N-Heights'),
	('350', 'Thriveni Pasupuleti', 'thriveni.pasupuleti@techigai.io', '.Net', '269', 'N-Heights'),
	('352', 'Pravalika Methuku', 'pravalika.methuku@techigai.io', 'Data Engineering', '433', 'Aurobindo'),
	('353', 'Vandana Killari', 'vandana.killari@techigai.io', 'Python', '125', 'N-Heights'),
	('354', 'Aishwarya Guduru', 'aishwarya.guduru@techigai.io', 'JS', '177', 'Aurobindo'),
	('356', 'Kasyap Velavarthipati', 'kasyap.velavarthipati@techigai.io', 'Platform Engineering', '175', 'N-Heights'),
	('357', 'Jaidev Cherakani', 'jaidev.cherakani@techigai.io', '.Net', '269', 'N-Heights'),
	('358', 'Amrutha Ittamsetty', 'amrutha.Ittamsetty@techigai.io', 'JS', '176', 'N-Heights'),
	('359', 'Praneeth Polamarasetti', 'praneeth.polamarasetti@techigai.io', '.NET', '176', 'N-Heights'),
	('360', 'Hemanth Pidugu', 'hemanth.pidugu@techigai.io', '.NET', '269', 'N-Heights'),
	('361', 'Divya Chinera', 'divya.chinera@techigai.io', '.NET', '182', 'N-Heights'),
	('362', 'Jyoshna Korada', 'jyoshna.korada@techigai.io', 'JS', '269', 'N-Heights'),
	('363', 'Harini Bathula', 'harini.bathula@techigai.io', 'ROR', '338', 'Aurobindo'),
	('364', 'Sravya Kosuri', 'sravya.kosuri@techigai.io', 'BA', '174', 'N-Heights'),
	('365', 'Harikrishna Konatala', 'harikrishna.konatala@techigai.io', 'Data Engineering', '391', 'Aurobindo'),
	('368', 'Abhishek Choudhary', 'abhishek.choudhary@techigai.io', 'Java', '210', 'Aurobindo'),
	('370', 'Pavani Chigurupati', 'pavani.chigurupati@techigai.io', 'Java', '210', 'Aurobindo'),
	('371', 'Aswitha Vejarla', 'aswitha.vejarla@techigai.io', '.NET', '176', 'N-Heights'),
	('372', 'Lokesh Sepuri', 'lokesh.sepuri@techigai.io', 'Java', '210', 'Aurobindo'),
	('373', 'Varshith Gate', 'varshith.gate@techigai.io', 'Data Engineering', '251', 'Aurobindo'),
	('374', 'Nagendra Palempalli', 'nagendra.palempalli@techigai.io', 'Data Engineering', '126', 'Aurobindo'),
	('376', 'Koushiknath Bingi', 'koushiknath.bingi@techigai.io', 'Front End', '166', 'N-Heights'),
	('377', 'Thanmai Chinnakotla', 'thanmai.chinnakotla@techigai.io', '.NET', '176', 'N-Heights'),
	('379', 'Rajesh Kuruba', 'rajesh.kuruba@techigai.io', '.NET', '122', 'N-Heights'),
	('385', 'Shashank Vasikarla', 'shashank.vasikarla@techigai.io', 'Quality Engineering', '190', 'Aurobindo '),
	('386', 'Madhavi Potnuru', 'Madhavi.potnuru@techigai.io', 'Admin', '200', 'N-Heights'),
	('387', 'Waseem Mohammed', 'waseem.mohammed@techigai.io', '.NET', '124', 'N-Heights'),
	('388', 'Pratap Jajjara', 'pratap.jajjara@techigai.io', 'PHP', '174', 'N-Heights'),
	('389', 'Mounika Cherukuri', 'mounika.cherukuri@techigai.io', 'Quality Engineering', '122', 'N-Heights'),
	('390', 'Srinivas Kunnatati', 'srinivas.kunnatati@techigai.io', 'Quality Engineering', '183', 'N-Heights'),
	('391', 'Kranthi Bondalkunta', 'kranthi.bondalkunta@techigai.io', 'Quality Engineering', '190', 'Aurobindo '),
	('392', 'UdayKiran Barra', 'udaykiran.barra@techigai.io', 'Data Engineering', '130', 'Aurobindo '),
	('394', 'Mrudhu Karimerakala', 'mrudhu.karimerakala@techigai.io', 'HR', '200', 'N-Heights'),
	('396', 'Seshu Kumar Maddirala', 'seshu.maddirala@techigai.io', 'PHP', '388', 'N-Heights'),
	('397', 'VENKAT S', 'Venkat.S@techigai.io', 'Admin', '200', 'N-Heights'),
	('399', 'Dileep Dodla', 'dileep.dodla@techigai.io', 'Python', '125', 'N-Heights'),
	('401', 'Chaitanya Kona', 'chaitanya.kona@techigai.io', 'UX', '127', 'N-Heights'),
	('403', 'Rajesh Donepudi', 'rajesh.donepudi@techigai.io', '.NET', '122', 'N-Heights'),
	('405', 'Jhansi Thangudu', 'jhansi.thangudu@techigai.io ', 'Quality Engineering', '465', 'N-Heights'),
	('406', 'Vamshi Maddela', 'vamshi.maddela@techigai.io', 'Quality Engineering', '179', 'N-Heights'),
	('407', 'Soumya Thallapelly', 'soumya.thallapelly@techigai.io ', 'Quality Engineering', '174', 'N-Heights'),
	('408', 'Sushma Manadalapu', 'sushma.manadalapu@techigai.io', 'Quality Engineering', '179', 'N-Heights'),
	('409', 'Lakshmi Pudi', 'lakshmi.pudi@techigai.io  ', 'Quality Engineering', '183', 'N-Heights'),
	('410', 'Balaveeraiah Yarabikki', 'balaveeraiah.yarabikki@techigai.io', 'TA', '189', 'N-Heights'),
	('411', 'Sowdamini Karyampudi', 'sowdamini.karyampudi@techigai.io', 'UX', '122', 'N-Heights'),
	('412', 'Janaki Thummeti', 'janaki.thummeti@techigai.io', 'Finance', '165', 'N-Heights'),
	('413', 'Bhargav Jalagadugula', 'bhargav.jalagadugula@techigai.io', 'Quality Engineering', '179', 'N-Heights'),
	('414', 'Venkat Jevisetti', 'venkat.jevisetti@techigai.io', '.NET', '195', 'N-Heights'),
	('416', 'Ashish Buddaraju', 'ashish.buddaraju@techigai.io', 'Quality Engineering', '179', 'Aurobindo'),
	('417', 'Avinash Kumar', 'avinash.kumar@techigai.io', 'BA', '127', 'N-Heights'),
	('419', 'Karthik Mediboina', 'karthik.mediboina@techigai.io', 'Data Engineering', '266', 'Aurobindo'),
	('420', 'Rahul Chowduvada', 'rahul.chowduvada@techigai.io', 'Data Engineering', '391', 'Aurobindo'),
	('422', 'Bharadwaj Manda', 'bharadwaj.manda@techigai.io', 'Data Engineering', '130', 'Aurobindo'),
	('423', 'Avinash Bevara', 'avinash.bevara@techigai.io', 'Data Engineering', '196', 'Aurobindo'),
	('425', 'Tulasidhar Mathamsetti', 'tulasidhar.mathamsetti@techigai.io', 'Data Engineering', '343', 'Aurobindo'),
	('426', 'Sreevalli Bontha', 'sreevalli.bontha@techigai.io', 'Data Engineering', '266', 'Aurobindo'),
	('427', 'Ram Giduturi', 'ram.giduturi@techigai.io', 'Data Engineering', '208', 'Aurobindo'),
	('428', 'Pawan Jagadala', 'pawan.jagadala@techigai.io', '.Net', '269', 'N-Heights'),
	('429', 'Manveet Devaguptapu', 'manveet.devaguptapu@techigai.io', 'PHP', '396', 'N-Heights'),
	('430', 'Ravishankar Yadav', 'ravishankar.yadav@techigai.io', 'ROR', '194', 'Aurobindo'),
	('431', 'Dinesh Pokala', 'dinesh.pokala@techigai.io', 'RPA', '175', 'N-Heights'),
	('433', 'Veera Putchala', 'veera.putchala@techigai.io', 'Data Engineering', '208', 'Aurobindo'),
	('434', 'Serin Sabu', 'serin.sabu@techigai.io', 'iOS', '224', 'Aurobindo'),
	('436', 'Prashanth Gorenkala', 'prashanth.gorenkala@techigai.io', 'Admin', '200', 'N-Heights'),
	('437', 'Shiva Gurram', 'shiva.gurram@techigai.io', 'Training', '124', 'Training center'),
	('438', 'Prabhakar Keshapally', 'prabhakar.keshapally@techigai.io', 'Data Engineering', '391', 'Aurobindo'),
	('439', 'Swamy Bethala', 'swamy.bethala@techigai.io', 'Data Engineering', '391', 'Aurobindo'),
	('440', 'Lahari Menta', 'lahari.menta@techigai.io', 'Quality Engineering', '183', 'N-Heights'),
	('441', 'Madhuri Jangeti', 'madhuri.jangeti@techigai.io', 'Training', '124', 'Training center'),
	('442', 'Pujitha Gurugari', 'pujitha.gurugari@techigai.io', 'Training', '124', 'Training center'),
	('443', 'Sanjitha Kalidindi', 'sanjitha.kalidindi@techigai.io', 'Training', '124', 'Training center'),
	('444', 'Harshitha Velivela', 'harshitha.velivela@techigai.io', 'Training', '124', 'Training center'),
	('445', 'Deepika Shamala', 'deepika.shamala@techigai.io', 'Training', '124', 'Training center'),
	('446', 'Pranathi Chaboli', 'pranathi.chaboli@techigai.io', 'Training', '124', 'Training center'),
	('447', 'Ramya Rangisetti', 'ramya.rangisetti@techigai.io', 'Training', '124', 'Training center'),
	('448', 'Purnima Mekala', 'purnima.mekala@techigai.io', 'Training', '124', 'Training center'),
	('449', 'Rishikesh Voruganti', 'rishikesh.voruganti@techigai.io', 'Quality Engineering', '179', 'N-Heights'),
	('451', 'Mounika Narlabai', '  mounika.narlabai@techigai.io', 'Training', '124', 'Training center'),
	('452', 'Sushma Gannoju', 'sushma.gannoju@techigai.io', 'Quality Engineering', '183', 'N-Heights'),
	('453', 'Keerthana Minda', 'keerthana.minda@techigai.io', 'Quality Engineering', '347', 'N-Heights'),
	('456', 'Abhiram Veerapaneni', 'abhiram.veerapaneni@techigai.io', 'Java', '190', 'Aurobindo'),
	('457', 'Swetha Sadar', 'swetha.sadar@techigai.io', 'Quality Engineering', '347', 'N-Heights'),
	('459', 'Kavitha Karamtoth', 'kavitha.karamtoth@techigai.io', 'Quality Engineering', '129', 'N-Heights'),
	('460', 'Sunny Bundullolu', 'sunny.bundullolu@techigai.io', 'Mobile', '224', 'Aurobindo'),
	('461', 'Naresh Kummari', 'naresh.kummari@techigai.io', 'Quality Engineering', '465', 'N-Heights'),
	('462', 'Vishnu Chimmani', 'vishnu.chimmani@techigai.io', 'Quality Engineering', '216', 'N-Heights'),
	('463', 'Krishna Arepally', 'krishna.arepally@techigai.io', 'Quality Engineering', '147', 'N-Heights'),
	('464', 'Praveen Bejjenki', 'praveen.bejjenki@techigai.io', 'Quality Engineering', '389', 'N-Heights'),
	('465', 'Shilpa Vagaroor', 'shilpa.vagaroor@techigai.io', 'Quality Engineering', '122', 'Virtual'),
	('466', 'Chinnammalu Peddinti', 'chinnammalu.peddinti@techigai.io', 'Java', '210', 'Aurobindo'),
	('467', 'Bindu Bonthu', 'bindu.bonthu@techigai.io', 'PHP', '396', 'N-Heights'),
	('468', 'Rakesh Jala', '   rakesh.jala@techigai.io', 'Data Engineering', '391', 'Aurobindo'),
	('469', 'Sasi Yalamaddi', 'sasi.yalamaddi@techigai.io', 'JS', '177', 'Aurobindo'),
	('473', 'Ekta Motapothula', 'ekta.motapothula@techigai.io', 'Data Engineering', '196', 'Aurobindo'),
	('474', 'Suketh Kothalanka', 'suketh.kothalanka@techigai.io', 'Training', '122', 'Training center'),
	('476', 'Pradeepa Rayarapu', 'pradeepa.rayarapu@techigai.io', 'Data Engineering', '343', 'Aurobindo'),
	('477', 'Akshaya Kesagani', 'akshaya.kesagani@techigai.io', 'Data Engineering', '196', 'Aurobindo'),
	('478', 'Supraja Nandyala', 'supraja.nandyala@techigai.io', 'Data Engineering', '196', 'Aurobindo'),
	('481', 'Sathvik Devulapally', 'sathvik.devulapally@techigai.io', 'Data Engineering', '129', 'Training center'),
	('483', 'Sumanth Inturi', 'sumanth.inturi@techigai.io', 'Data Engineering', '433', 'Aurobindo'),
	('491', 'Santhosh Anumolu', 'santhosh.anumolu@techigai.io', 'Training', '175', 'Training center'),
	('495', 'Uttej Botta', 'uttej.botta@techigai.io', 'Data Engineering', '391', 'Aurobindo'),
	('497', 'Suresh Panguluri', 'suresh.panguluri@techigai.io', 'Mobile', '224', 'Aurobindo'),
	('499', 'Ravi Varma Yalamanchili', 'ravi.yalamanchili@techigai.io', 'Data Engineering', '506', 'Aurobindo'),
	('500', 'Shirisha Muthineni', 'shirisha.muthineni@techigai.io', 'Data Engineering', '433', 'Aurobindo'),
	('501', 'Navya Charlakola', 'navya.charlakola@techigai.io', 'Data Engineering', '433', 'Aurobindo'),
	('503', 'Mariya Rubab', 'mariya.rubab@techigai.io', 'Data Engineering', '391', 'Aurobindo'),
	('506', 'Deepak Chevendra', 'deepak.chevendra@techigai.io', 'Project Management', '391', 'Aurobindo'),
	('507', 'Rana Kyasaram', 'rana.kyasaram@techigai.io', 'PHP', '388', 'N-Heights'),
	('509', 'Madhavi Mavuri', 'madhavi.mavuri@techigai.io', 'Infor', '195', 'N-Heights'),
	('510', 'Qayyum Shareef', 'qayyum.shareef@techigai.io', 'JS', '224', 'Aurobindo'),
	('511', 'Meghana Kadainty', 'meghana.kadainty@techigai.io', 'Android', '519', 'N-Heights'),
	('512', 'Sai Kiran Shrinath', 'saikiran.shrinath@techigai.io', 'Data Engineering', '266', 'Aurobindo'),
	('513', 'Saketh Nagamalla', 'saketh.nagamalla@techigai.io', 'Data Engineering', '391', 'Aurobindo'),
	('514', 'Shruti Rallapalli', 'shruti.rallapalli@techigai.io', 'HR', '200', 'N-Heights'),
	('515', 'Karishma Musunuri', 'karishma.musunuri@techigai.io', 'HR', '200', 'N-Heights'),
	('516', 'Swathi Govindapur', 'swathi.govindapur@techigai.io', 'Admin', '200', 'N-Heights'),
	('517', 'Akhil Grandhi', 'akhil.grandhi@techigai.io', 'Data Engineering', '266', 'Aurobindo'),
	('518', 'Sravani Chilakala', 'sravani.chilakala@techigai.io', 'Data Engineering', '208', 'Aurobindo'),
	('519', 'Bishnu Prasad', 'bishnu.prasad@techigai.io', 'Android', '190', 'Aurobindo'),
	('520', 'Naresh Mallela', 'naresh.mallela@techigai.io', 'Data Engineering', '391', 'Aurobindo'),
	('521', 'Pavan Kancharla', 'pavan.kancharla@techigai.io', 'RPA', '175', 'N-Heights'),
	('522', 'Ashok Bonu', 'ashok.bonu@techigai.io', 'Data Engineering', '391', 'Aurobindo'),
	('523', 'Siva Gundibilli', 'siva.gundibilli@techigai.io', 'RPA', '175', 'N-Heights'),
	('524', 'Hemasree Ambati', 'hemasree.ambati@techigai.io', 'Data Engineering', '391', 'Aurobindo'),
	('525', 'Pavani Badaballa', 'pavani.badaballa@techigai.io', 'Data Engineering', '391', 'Aurobindo'),
	('526', 'Debu Edwards', 'debu.edwards@techigai.io', 'UX', '122', 'N-Heights')